/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stdGovernance from "./stdGovernance";
export type { stdGovernance };
export type { Box } from "./Box";
export type { DirtyDeedsToken } from "./DirtyDeedsToken";
