/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stdGovernance from "./stdGovernance";
export { Box__factory } from "./Box__factory";
export { DirtyDeedsToken__factory } from "./DirtyDeedsToken__factory";
