/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorD4C } from "./GovernorD4C";
export type { Timelock } from "./Timelock";
export type { TimelockController } from "./TimelockController";
